# Generated by Django 6.1.1 on 2026-09-30 09:12

import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeScaleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=5, unique=True)),
                ('grade_point', models.IntegerField()),
                ('min_mark', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_mark', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['-grade_point'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('STUDENT', 'Student'), ('FACULTY', 'Faculty'), ('ADMIN', 'Admin')], db_index=True, default='STUDENT', max_length=20)),
                ('department', models.CharField(default='Computer Science & Engineering', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('avatar_color', models.CharField(default='#5B5BD6', max_length=30)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=150)),
                ('user_role', models.CharField(max_length=30)),
                ('action', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('record_id', models.CharField(blank=True, max_length=100)),
                ('old_value', models.JSONField(blank=True, default=dict)),
                ('new_value', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FacultyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_id', models.CharField(db_index=True, max_length=30, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('department', models.CharField(default='Computer Science & Engineering', max_length=100)),
                ('designation', models.CharField(default='Assistant Professor', max_length=100)),
                ('cabin', models.CharField(default='CSE Block - Room 304', max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['faculty_id'],
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('ACADEMIC', 'Academic'), ('EXAM', 'Examination'), ('PLACEMENT', 'Placement & Internship'), ('PROJECT', 'Project Review'), ('EVENT', 'Technical Symposium & Hackathon')], default='ACADEMIC', max_length=30)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('target_year', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_notices', to='core.facultyprofile')),
            ],
            options={
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('domain', models.CharField(default='Artificial Intelligence & Cloud Computing', max_length=150)),
                ('year', models.IntegerField(default=4)),
                ('academic_year', models.CharField(default='2026-2027', max_length=20)),
                ('abstract', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposed'), ('IN_PROGRESS', 'In Progress'), ('REVIEW_SCHEDULED', 'Review Scheduled'), ('COMPLETED', 'Completed')], default='IN_PROGRESS', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guided_projects', to='core.facultyprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_number', models.IntegerField(default=1)),
                ('review_name', models.CharField(default='Project Review 1', max_length=100)),
                ('review_date', models.DateTimeField()),
                ('venue', models.CharField(default='CSE Project Lab 1', max_length=100)),
                ('max_marks', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('marks_awarded', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('comments', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('PENDING_REVISION', 'Pending Revision')], default='SCHEDULED', max_length=30)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.project')),
            ],
            options={
                'ordering': ['review_date'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_no', models.CharField(db_index=True, max_length=30, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('department', models.CharField(default='Computer Science & Engineering', max_length=100)),
                ('year', models.IntegerField(choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4')], default=3)),
                ('section', models.CharField(default='A', max_length=5)),
                ('current_semester', models.IntegerField(default=5)),
                ('admission_year', models.IntegerField(default=2023)),
                ('overall_cgpa', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('overall_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('overall_attendance_pct', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['register_no'],
            },
        ),
        migrations.CreateModel(
            name='SemesterResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('academic_year', models.CharField(default='2025-2026', max_length=20)),
                ('sgpa', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('total_credits', models.IntegerField(default=0)),
                ('earned_credits', models.IntegerField(default=0)),
                ('total_marks_obtained', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('total_max_marks', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('status', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('WITHHELD', 'Withheld')], default='PASS', max_length=20)),
                ('published_date', models.DateField(default=datetime.date.today)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_results', to='core.studentprofile')),
            ],
            options={
                'ordering': ['student', 'semester'],
                'unique_together': {('student', 'semester')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='students',
            field=models.ManyToManyField(related_name='projects', to='core.studentprofile'),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('department', models.CharField(default='Computer Science & Engineering', max_length=100)),
                ('semester', models.IntegerField(default=5)),
                ('year', models.IntegerField(choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4')], default=3)),
                ('credits', models.IntegerField(default=4)),
                ('syllabus_summary', models.TextField(blank=True)),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='core.facultyprofile')),
            ],
            options={
                'ordering': ['semester', 'code'],
            },
        ),
        migrations.CreateModel(
            name='InternalAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('max_marks', models.DecimalField(decimal_places=2, default=50.0, max_digits=5)),
                ('weightage_pct', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('date', models.DateField(default=datetime.date.today)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='core.subject')),
            ],
            options={
                'ordering': ['subject', 'date'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('session_slot', models.CharField(default='09:00 - 10:00 AM', max_length=50)),
                ('topic', models.CharField(blank=True, max_length=200)),
                ('class_year', models.IntegerField(default=3)),
                ('class_section', models.CharField(default='A', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conducted_sessions', to='core.facultyprofile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='core.subject')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('due_date', models.DateTimeField(db_index=True)),
                ('max_marks', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('year', models.IntegerField(default=3)),
                ('section', models.CharField(default='A', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_assignments', to='core.facultyprofile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.subject')),
            ],
            options={
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='InternalMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_absent', models.BooleanField(default=False)),
                ('remarks', models.CharField(blank=True, max_length=150)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='core.internalassessment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_marks', to='core.studentprofile')),
            ],
            options={
                'ordering': ['student__register_no'],
                'unique_together': {('assessment', 'student')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('OD', 'On Duty'), ('LATE', 'Late')], default='PRESENT', max_length=20)),
                ('remarks', models.CharField(blank=True, max_length=150)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='core.attendancesession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='core.studentprofile')),
            ],
            options={
                'ordering': ['student__register_no'],
                'unique_together': {('session', 'student')},
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('LATE', 'Late'), ('GRADED', 'Graded')], default='PENDING', max_length=20)),
                ('submission_text', models.TextField(blank=True)),
                ('file_url', models.CharField(blank=True, max_length=300)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('marks_awarded', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('faculty_feedback', models.TextField(blank=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to='core.studentprofile')),
            ],
            options={
                'ordering': ['assignment__due_date'],
                'unique_together': {('assignment', 'student')},
            },
        ),
        migrations.CreateModel(
            name='ClassEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(default='2026-2027', max_length=20)),
                ('semester', models.IntegerField(default=5)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.studentprofile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.subject')),
            ],
            options={
                'unique_together': {('student', 'subject', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='SubjectGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_marks', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('external_marks', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total_marks', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('grade', models.CharField(choices=[('O', 'Outstanding (10)'), ('A+', 'Excellent (9)'), ('A', 'Very Good (8)'), ('B+', 'Good (7)'), ('B', 'Above Average (6)'), ('C', 'Average (5)'), ('U', 'Reappear / Fail (0)')], default='A', max_length=5)),
                ('grade_point', models.IntegerField(default=8)),
                ('result_status', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail')], default='PASS', max_length=10)),
                ('semester_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='core.semesterresult')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
            ],
            options={
                'unique_together': {('semester_result', 'subject')},
            },
        ),
    ]
